<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MonthlyWrappedSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('monthly_wrappeds')->truncate();

        $wrappeds = [
            [
                'wrapped_id'       => '2026-04',
                'label'            => 'apríl 2026',
                'month'            => 'apríl',
                'short'            => 'apr',
                'season'           => 'spring',
                'days_range'       => '813–842',
                'headline'         => 'mesiac vína a Schönbrunnu',
                'photos_count'     => 92,
                'top_day'          => '12. apr',
                'top_day_count'    => 27,
                'top_moment_title' => 'Víkend vo Viedni',
                'top_moment_place' => 'Viedeň, AT',
                'top_moment_id'    => 'wien-26',
                'bucket_count'     => 1,
                'bucket_txt'       => 'Víkend vo Viedni',
                'outro'            => 'Stálo to za tých 92 fotiek.',
                'is_top'           => false,
                'sort_order'       => 1,
            ],
            [
                'wrapped_id'       => '2026-03',
                'label'            => 'marec 2026',
                'month'            => 'marec',
                'short'            => 'mar',
                'season'           => 'spring',
                'days_range'       => '781–811',
                'headline'         => 'mesiac kávy a kartičiek',
                'photos_count'     => 41,
                'top_day'          => '24. mar',
                'top_day_count'    => 7,
                'top_moment_title' => 'Učenie na štátnice',
                'top_moment_place' => 'doma',
                'top_moment_id'    => 'statnice',
                'bucket_count'     => 0,
                'bucket_txt'       => null,
                'outro'            => 'Tri týždne, dva piloty Anki. Stálo to za to.',
                'is_top'           => false,
                'sort_order'       => 2,
            ],
            [
                'wrapped_id'       => '2026-02',
                'label'            => 'február 2026',
                'month'            => 'február',
                'short'            => 'feb',
                'season'           => 'winter',
                'days_range'       => '752–780',
                'headline'         => 'najfoto mesiac roka',
                'photos_count'     => 187,
                'top_day'          => '17. feb',
                'top_day_count'    => 23,
                'top_moment_title' => 'Tatry · 5 dní',
                'top_moment_place' => 'Štrbské Pleso',
                'top_moment_id'    => 'tatry-26',
                'bucket_count'     => 0,
                'bucket_txt'       => null,
                'outro'            => 'Priemer 6,7 fotiek na deň. Najviac za celý rok.',
                'is_top'           => true,
                'sort_order'       => 3,
            ],
            [
                'wrapped_id'       => '2026-01',
                'label'            => 'január 2026',
                'month'            => 'január',
                'short'            => 'jan',
                'season'           => 'winter',
                'days_range'       => '721–751',
                'headline'         => 'dva roky spolu',
                'photos_count'     => 38,
                'top_day'          => '21. jan',
                'top_day_count'    => 14,
                'top_moment_title' => '2. výročie',
                'top_moment_place' => 'reštaurácia STROM',
                'top_moment_id'    => 'vyrocie',
                'bucket_count'     => 0,
                'bucket_txt'       => null,
                'outro'            => '731. deň. Saint-Émilion, prvá fľaša.',
                'is_top'           => false,
                'sort_order'       => 4,
            ],
            [
                'wrapped_id'       => '2025-12',
                'label'            => 'december 2025',
                'month'            => 'december',
                'short'            => 'dec',
                'season'           => 'winter',
                'days_range'       => '690–720',
                'headline'         => 'prvé spoločné Vianoce u tvojich',
                'photos_count'     => 75,
                'top_day'          => '24. dec',
                'top_day_count'    => 18,
                'top_moment_title' => 'Vianoce u rodičov',
                'top_moment_place' => 'Trenčín',
                'top_moment_id'    => 'vianoce',
                'bucket_count'     => 0,
                'bucket_txt'       => null,
                'outro'            => 'Snežilo až po obed.',
                'is_top'           => false,
                'sort_order'       => 5,
            ],
            [
                'wrapped_id'       => '2025-11',
                'label'            => 'november 2025',
                'month'            => 'november',
                'short'            => 'nov',
                'season'           => 'autumn',
                'days_range'       => '660–689',
                'headline'         => 'tichý mesiac',
                'photos_count'     => 22,
                'top_day'          => '15. nov',
                'top_day_count'    => 5,
                'top_moment_title' => 'Doma, pomaly',
                'top_moment_place' => 'doma',
                'top_moment_id'    => null,
                'bucket_count'     => 1,
                'bucket_txt'       => 'Spraviť domácu pizzu',
                'outro'            => 'Nie každý mesiac musí mať veľký vrchol.',
                'is_top'           => false,
                'sort_order'       => 6,
            ],
        ];

        DB::table('monthly_wrappeds')->insert(array_map(fn($w) => array_merge($w, [
            'created_at' => now(),
            'updated_at' => now(),
        ]), $wrappeds));
    }
}
